apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    test: powerai-biggan
  name: gpu-biggan
  namespace: cloud-native-deployments-hp-ai
  selfLink: >-
    /apis/apps.openshift.io/v1/namespaces/cloud-native-deployments-hp-ai/deploymentconfigs/gpu-biggan
spec:
  replicas: 1
  selector:
    deploymentconfig: gpu-biggan
    test: powerai-biggan
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        deploymentconfig: gpu-biggan
        test: powerai-biggan
    spec:
      containers:
      - image: docker-registry.default.svc:5000/cloud-native-deployments-hp-ai/powerai:biggan-testdata
        imagePullPolicy: Always
        name: gpu-biggan-test
        env:
          - name: NVIDIA_VISIBLE_DEVICES
            value: all
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: "compute,utility"
          - name: NVIDIA_REQUIRE_CUDA
            value: "cuda>=5.0"
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   capabilities:
        #     drop: ["ALL"]
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        # volumeMounts:
        #   - mountPath: /data/ImageNet/ILSVRC2012/train
        #     name: volume-train-data
        #   - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        #     name: default-token-ljnb6
        #     readOnly: true
        resources:
          limits:
            nvidia.com/gpu: 4
      # volumes:
      # - name: volume-train-data
      #   persistentVolumeClaim:
      #     claimName: 10gb-rwo
      # - name: default-token-ljnb6
      #   secret:
      #     defaultMode: 420
      #     secretName: default-token-ljnb6
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - gpu-biggan-test
        from:
          kind: ImageStreamTag
          name: 'powerai:biggan-testdata'
          namespace: cloud-native-deployments-hp-ai
        lastTriggeredImage: >-
          docker-registry.default.svc:5000/cloud-native-deployments-hp-ai/powerai:biggan-testdata
      type: ImageChange
