apiVersion: v1
kind: Pod
metadata:
  name: pod-biggan
spec:
  restartPolicy: OnFailure
  containers:
  - image: docker-registry.default.svc:5000/cloud-native-deployments-hp-ai/powerai:biggan-testdata
    # command: ['sh', '-c', 'sleep 360000']
    imagePullPolicy: Always
    name: biggan-test
    # volumeMounts:
    #   - mountPath: /data/ImageNet/ILSVRC2012/train
    #     name: volume-train-data
    #     readOnly: true
    #   - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
    #     name: default-token-ljnb6
    #     readOnly: true
    env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        - name: NVIDIA_REQUIRE_CUDA
          value: "cuda>=5.0"
    # securityContext:
    #   allowPrivilegeEscalation: false
    #   capabilities:
    #     drop: ["ALL"]
    resources:
      limits:
        nvidia.com/gpu: 1
  # volumes:
  #   - name: volume-train-data
  #     persistentVolumeClaim:
  #       claimName: nfs2000
  #   - name: default-token-ljnb6
  #     secret:
  #       defaultMode: 420
  #       secretName: default-token-ljnb6
  serviceAccount: default
  serviceAccountName: default