apiVersion: v1
kind: Pod
metadata:
  name: test-biggan-w7p7g
  namespace: cloud-native-deployments-hp-ai
spec:
  containers:
    - image: >-
        docker-registry.default.svc:5000/cloud-native-deployments-hp-ai/powerai:biggan
      imagePullPolicy: Always
      name: biggan-test
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /data/ImageNet/ILSVRC2012/train
          name: volume-w41ds
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-ljnb6
          readOnly: true
      # env:
      #     - name: NVIDIA_VISIBLE_DEVICES
      #       value: all
      #     - name: NVIDIA_DRIVER_CAPABILITIES
      #       value: "compute,utility"
      #     - name: NVIDIA_REQUIRE_CUDA
      #       value: "cuda>=5.0"
      # securityContext:
      #   allowPrivilegeEscalation: false
      #   capabilities:
      #     drop: ["ALL"]
      # resources:
      #   limits:
      #     nvidia.com/gpu: 1
  dnsPolicy: ClusterFirst
  imagePullSecrets:
    - name: default-dockercfg-8jxdd
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
    - name: volume-w41ds
      persistentVolumeClaim:
        claimName: 5gb-rwx
    - name: default-token-ljnb6
      secret:
        defaultMode: 420
        secretName: default-token-ljnb6
